title: nilsso
author: Nils Olsson
email: nilso@enosis.net
description: My personal site
github_username: nilsso
github_dotfiles: dotfiles
base_hue: 210

defaults:
    - values:
        layout: "default"

kramdown:
    math_engine: +nil+

exclude:
    - node_modules
    - Gemfile
    - Gemfile.lock

plugins:
    - jekyll-toc
    - jekyll-katex

extensions: [fenced_code_blocks]
