title: nilsso
author: Nils Olsson
email: nilso@enosis.net
description: My personal site
#baseurl: "" # site subpath, e.g. /blog
#url: "" # site base hostname & protocol, e.g. http://example.com
twitter_username: #FuckTwitter
github_username: nilsso
github_dotfiles: dotfiles

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock

plugins:

extensions: [fenced_code_blocks]
