title: nilsso
author: Nils Olsson
email: nilso@enosis.net
description: My personal site
github_username: nilsso
github_dotfiles: dotfiles

defaults:
    - values:
        layout: "default"

exclude:
    - node_modules
    - Gemfile
    - Gemfile.lock

plugins:
    - jekyll-katex

extensions: [fenced_code_blocks]
