title: nilso
author: Nils Olsson
email: nilso@enosis.net
description: My personal site
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #FuckTwitter
github_username: SweedJesus
github_dotfiles: dotfiles

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock

plugins:
  - rouge
  - jekyll-toc
  #-jekyll-octicons
  #-jekyll-feed

#markdown: redcarpet
extensions: [fenced_code_blocks]
highlighter: rouge
#kramdown:
  #math_engine: mathjax
  #syntax_highlighter: rouge
